#pragma once
#include "Option.h"
#include "OptionType.h"

#include "AudioBitrateOption.h"
#include "AudioCopyOption.h"
#include "BitrateOption.h"
#include "CopyOption.h"
#include "DurationOption.h"
#include "FramerateOption.h"
#include "InputFileOption.h"
#include "MuteOption.h"
#include "OutputFileOption.h"
#include "OverwriteOption.h"
#include "ResolutionOption.h"
#include "StartTimeOption.h"