#pragma once
#include "pch.h"

#define WM_CUSTOM_VIEW_SIZE_CHANGED (WM_USER + 1)
#define WM_CUSTOM_CONVERSION_PROGRESS (WM_USER + 2)
#define WM_CUSTOM_CONVERSION_COMPLETED (WM_USER + 3)

#define CUSTOM_CMD_START 0xF000
#define ID_CUSTOM_MEDIA_CTRL_CHANGED (CUSTOM_CMD_START + 1)
#define ID_CUSTOM_MEDIA_CTRL_PLAYBACK_THREAD_CHANGED (CUSTOM_CMD_START + 2)
#define ID_CUSTOM_VIDEO_LOADED (CUSTOM_CMD_START + 3)

#define CUSTOM_TIMER_START 0xFF00
#define ID_TIMER_CONVERT_DLG (CUSTOM_TIMER_START + 1)
